### ISSUE TITLE
Using scipy's genetic algorithm for initial parameter estimation in gradient descent

### ISSUE THREAD

**Issue by zunzun** [AkihikoWatanabe/DBGD#1]
I see you are writing Python code for gradient descent optimization. The authors of scipy have added a genetic algorithm for initial parameter estimation for use in gradient descent. The module is named scipy.optimize.differential_evolution.

I have used scipy's Differential Evolution genetic algorithm to determine initial parameters for fitting a double Lorentzian peak equation to Raman spectroscopy data and found that the results were excellent. The GitHub project, with a test spectroscopy data file, is:

https://github.com/zunzun/RamanSpectroscopyFit

If you have any questions, please let me know. My background is in nuclear engineering and industrial radiation physics, and I love Python, so I will be glad to help.

**Comment by AkihikoWatanabe** [comment]
Thank you for the good advise and I'm sorry for the late replying.
I don't know about Differential Evolution genetic algorithm, so I would like to refer to your repository and scipy's documentation.

**Comment by zunzun** [comment]
I am glad to help, and am glad to answer any questions. Please email directly to zunzun@zunzun.com, I no longer use github.

James
